/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ApiAdvisorRouteImport } from './routes/api.advisor'
import { Route as ApiAdvisorChatRouteImport } from './routes/api.advisor-chat'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as BuyerFavoritesRouteImport } from './routes/buyer.favorites'
import { Route as BuyerMessagesRouteImport } from './routes/buyer.messages'
import { Route as BuyerProductsRouteImport } from './routes/buyer.products'
import { Route as BuyerProfileRouteImport } from './routes/buyer.profile'
import { Route as BuyerServicesRouteImport } from './routes/buyer.services'
import { Route as ElderCallbackRouteImport } from './routes/elder.callback'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as SellerAiAdvisorRouteImport } from './routes/seller.ai-advisor'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as SellerInterviewRouteImport } from './routes/seller.interview'
import { Route as SellerMessagesRouteImport } from './routes/seller.messages'
import { Route as SellerOnboardingRouteImport } from './routes/seller.onboarding'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerProfileRouteImport } from './routes/seller.profile'
import { Route as SellerServicesRouteImport } from './routes/seller.services'
import { Route as BuyerProductIdRouteImport } from './routes/buyer.product.$id'
import { Route as BuyerServiceIdRouteImport } from './routes/buyer.service.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorRoute = ApiAdvisorRouteImport.update({
  id: '/api/advisor',
  path: '/api/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorChatRoute = ApiAdvisorChatRouteImport.update({
  id: '/api/advisor-chat',
  path: '/api/advisor-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerFavoritesRoute = BuyerFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerMessagesRoute = BuyerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerProductsRoute = BuyerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerProfileRoute = BuyerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerServicesRoute = BuyerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => BuyerRoute,
} as any)
const ElderCallbackRoute = ElderCallbackRouteImport.update({
  id: '/elder/callback',
  path: '/elder/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAiAdvisorRoute = SellerAiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SellerRoute,
} as any)
const SellerInterviewRoute = SellerInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => SellerRoute,
} as any)
const SellerMessagesRoute = SellerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProfileRoute = SellerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SellerRoute,
} as any)
const SellerServicesRoute = SellerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SellerRoute,
} as any)
const BuyerProductIdRoute = BuyerProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerServiceIdRoute = BuyerServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => BuyerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/buyer/favorites': typeof BuyerFavoritesRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/products': typeof BuyerProductsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/services': typeof BuyerServicesRoute
  '/elder/callback': typeof ElderCallbackRoute
  '/seller/ai-advisor': typeof SellerAiAdvisorRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/interview': typeof SellerInterviewRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/services': typeof SellerServicesRoute
  '/buyer/': typeof BuyerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
  '/buyer/service/$id': typeof BuyerServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/buyer/favorites': typeof BuyerFavoritesRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/products': typeof BuyerProductsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/services': typeof BuyerServicesRoute
  '/elder/callback': typeof ElderCallbackRoute
  '/seller/ai-advisor': typeof SellerAiAdvisorRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/interview': typeof SellerInterviewRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/services': typeof SellerServicesRoute
  '/buyer': typeof BuyerIndexRoute
  '/seller': typeof SellerIndexRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
  '/buyer/service/$id': typeof BuyerServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/api/advisor': typeof ApiAdvisorRoute
  '/api/advisor-chat': typeof ApiAdvisorChatRoute
  '/buyer/favorites': typeof BuyerFavoritesRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/products': typeof BuyerProductsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/services': typeof BuyerServicesRoute
  '/elder/callback': typeof ElderCallbackRoute
  '/seller/ai-advisor': typeof SellerAiAdvisorRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/interview': typeof SellerInterviewRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/services': typeof SellerServicesRoute
  '/buyer/': typeof BuyerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
  '/buyer/service/$id': typeof BuyerServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer'
    | '/login'
    | '/seller'
    | '/api/advisor'
    | '/api/advisor-chat'
    | '/buyer/favorites'
    | '/buyer/messages'
    | '/buyer/products'
    | '/buyer/profile'
    | '/buyer/services'
    | '/elder/callback'
    | '/seller/ai-advisor'
    | '/seller/analytics'
    | '/seller/interview'
    | '/seller/messages'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/seller/services'
    | '/buyer/'
    | '/seller/'
    | '/buyer/product/$id'
    | '/buyer/service/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/advisor'
    | '/api/advisor-chat'
    | '/buyer/favorites'
    | '/buyer/messages'
    | '/buyer/products'
    | '/buyer/profile'
    | '/buyer/services'
    | '/elder/callback'
    | '/seller/ai-advisor'
    | '/seller/analytics'
    | '/seller/interview'
    | '/seller/messages'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/seller/services'
    | '/buyer'
    | '/seller'
    | '/buyer/product/$id'
    | '/buyer/service/$id'
  id:
    | '__root__'
    | '/'
    | '/buyer'
    | '/login'
    | '/seller'
    | '/api/advisor'
    | '/api/advisor-chat'
    | '/buyer/favorites'
    | '/buyer/messages'
    | '/buyer/products'
    | '/buyer/profile'
    | '/buyer/services'
    | '/elder/callback'
    | '/seller/ai-advisor'
    | '/seller/analytics'
    | '/seller/interview'
    | '/seller/messages'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/seller/services'
    | '/buyer/'
    | '/seller/'
    | '/buyer/product/$id'
    | '/buyer/service/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerRoute: typeof BuyerRouteWithChildren
  LoginRoute: typeof LoginRoute
  SellerRoute: typeof SellerRouteWithChildren
  ApiAdvisorRoute: typeof ApiAdvisorRoute
  ApiAdvisorChatRoute: typeof ApiAdvisorChatRoute
  ElderCallbackRoute: typeof ElderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor': {
      id: '/api/advisor'
      path: '/api/advisor'
      fullPath: '/api/advisor'
      preLoaderRoute: typeof ApiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor-chat': {
      id: '/api/advisor-chat'
      path: '/api/advisor-chat'
      fullPath: '/api/advisor-chat'
      preLoaderRoute: typeof ApiAdvisorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/favorites': {
      id: '/buyer/favorites'
      path: '/favorites'
      fullPath: '/buyer/favorites'
      preLoaderRoute: typeof BuyerFavoritesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/messages': {
      id: '/buyer/messages'
      path: '/messages'
      fullPath: '/buyer/messages'
      preLoaderRoute: typeof BuyerMessagesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/products': {
      id: '/buyer/products'
      path: '/products'
      fullPath: '/buyer/products'
      preLoaderRoute: typeof BuyerProductsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/profile': {
      id: '/buyer/profile'
      path: '/profile'
      fullPath: '/buyer/profile'
      preLoaderRoute: typeof BuyerProfileRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/services': {
      id: '/buyer/services'
      path: '/services'
      fullPath: '/buyer/services'
      preLoaderRoute: typeof BuyerServicesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/elder/callback': {
      id: '/elder/callback'
      path: '/elder/callback'
      fullPath: '/elder/callback'
      preLoaderRoute: typeof ElderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/ai-advisor': {
      id: '/seller/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/seller/ai-advisor'
      preLoaderRoute: typeof SellerAiAdvisorRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/interview': {
      id: '/seller/interview'
      path: '/interview'
      fullPath: '/seller/interview'
      preLoaderRoute: typeof SellerInterviewRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/messages': {
      id: '/seller/messages'
      path: '/messages'
      fullPath: '/seller/messages'
      preLoaderRoute: typeof SellerMessagesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/onboarding': {
      id: '/seller/onboarding'
      path: '/onboarding'
      fullPath: '/seller/onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/profile': {
      id: '/seller/profile'
      path: '/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof SellerProfileRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/services': {
      id: '/seller/services'
      path: '/services'
      fullPath: '/seller/services'
      preLoaderRoute: typeof SellerServicesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/buyer/product/$id': {
      id: '/buyer/product/$id'
      path: '/product/$id'
      fullPath: '/buyer/product/$id'
      preLoaderRoute: typeof BuyerProductIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/service/$id': {
      id: '/buyer/service/$id'
      path: '/service/$id'
      fullPath: '/buyer/service/$id'
      preLoaderRoute: typeof BuyerServiceIdRouteImport
      parentRoute: typeof BuyerRoute
    }
  }
}

interface BuyerRouteChildren {
  BuyerFavoritesRoute: typeof BuyerFavoritesRoute
  BuyerMessagesRoute: typeof BuyerMessagesRoute
  BuyerProductsRoute: typeof BuyerProductsRoute
  BuyerProfileRoute: typeof BuyerProfileRoute
  BuyerServicesRoute: typeof BuyerServicesRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  BuyerProductIdRoute: typeof BuyerProductIdRoute
  BuyerServiceIdRoute: typeof BuyerServiceIdRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerFavoritesRoute: BuyerFavoritesRoute,
  BuyerMessagesRoute: BuyerMessagesRoute,
  BuyerProductsRoute: BuyerProductsRoute,
  BuyerProfileRoute: BuyerProfileRoute,
  BuyerServicesRoute: BuyerServicesRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  BuyerProductIdRoute: BuyerProductIdRoute,
  BuyerServiceIdRoute: BuyerServiceIdRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

interface SellerRouteChildren {
  SellerAiAdvisorRoute: typeof SellerAiAdvisorRoute
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerInterviewRoute: typeof SellerInterviewRoute
  SellerMessagesRoute: typeof SellerMessagesRoute
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerProfileRoute: typeof SellerProfileRoute
  SellerServicesRoute: typeof SellerServicesRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAiAdvisorRoute: SellerAiAdvisorRoute,
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerInterviewRoute: SellerInterviewRoute,
  SellerMessagesRoute: SellerMessagesRoute,
  SellerOnboardingRoute: SellerOnboardingRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerProfileRoute: SellerProfileRoute,
  SellerServicesRoute: SellerServicesRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerRoute: BuyerRouteWithChildren,
  LoginRoute: LoginRoute,
  SellerRoute: SellerRouteWithChildren,
  ApiAdvisorRoute: ApiAdvisorRoute,
  ApiAdvisorChatRoute: ApiAdvisorChatRoute,
  ElderCallbackRoute: ElderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
