/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachAndShareRouteImport } from './routes/teach-and-share'
import { Route as TheirExpertiseRouteImport } from './routes/their-expertise'
import { Route as ExpertExpertIdRouteImport } from './routes/expert.$expertId'
import { Route as MeetingBookingIdRouteImport } from './routes/meeting.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachAndShareRoute = TeachAndShareRouteImport.update({
  id: '/teach-and-share',
  path: '/teach-and-share',
  getParentRoute: () => rootRouteImport,
} as any)
const TheirExpertiseRoute = TheirExpertiseRouteImport.update({
  id: '/their-expertise',
  path: '/their-expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertExpertIdRoute = ExpertExpertIdRouteImport.update({
  id: '/expert/$expertId',
  path: '/expert/$expertId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingBookingIdRoute = MeetingBookingIdRouteImport.update({
  id: '/meeting/$bookingId',
  path: '/meeting/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teach-and-share': typeof TeachAndShareRoute
  '/their-expertise': typeof TheirExpertiseRoute
  '/expert/$expertId': typeof ExpertExpertIdRoute
  '/meeting/$bookingId': typeof MeetingBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teach-and-share': typeof TeachAndShareRoute
  '/their-expertise': typeof TheirExpertiseRoute
  '/expert/$expertId': typeof ExpertExpertIdRoute
  '/meeting/$bookingId': typeof MeetingBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teach-and-share': typeof TeachAndShareRoute
  '/their-expertise': typeof TheirExpertiseRoute
  '/expert/$expertId': typeof ExpertExpertIdRoute
  '/meeting/$bookingId': typeof MeetingBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teach-and-share'
    | '/their-expertise'
    | '/expert/$expertId'
    | '/meeting/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teach-and-share'
    | '/their-expertise'
    | '/expert/$expertId'
    | '/meeting/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/teach-and-share'
    | '/their-expertise'
    | '/expert/$expertId'
    | '/meeting/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeachAndShareRoute: typeof TeachAndShareRoute
  TheirExpertiseRoute: typeof TheirExpertiseRoute
  ExpertExpertIdRoute: typeof ExpertExpertIdRoute
  MeetingBookingIdRoute: typeof MeetingBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach-and-share': {
      id: '/teach-and-share'
      path: '/teach-and-share'
      fullPath: '/teach-and-share'
      preLoaderRoute: typeof TeachAndShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/their-expertise': {
      id: '/their-expertise'
      path: '/their-expertise'
      fullPath: '/their-expertise'
      preLoaderRoute: typeof TheirExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/$expertId': {
      id: '/expert/$expertId'
      path: '/expert/$expertId'
      fullPath: '/expert/$expertId'
      preLoaderRoute: typeof ExpertExpertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$bookingId': {
      id: '/meeting/$bookingId'
      path: '/meeting/$bookingId'
      fullPath: '/meeting/$bookingId'
      preLoaderRoute: typeof MeetingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeachAndShareRoute: TeachAndShareRoute,
  TheirExpertiseRoute: TheirExpertiseRoute,
  ExpertExpertIdRoute: ExpertExpertIdRoute,
  MeetingBookingIdRoute: MeetingBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
